version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "backend-viveak"
s3_prefix = "backend-viveak"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CodeSigningConfigArn=\"none\" Environment=\"dev\" PermissionsBoundary=\"none\" SecretPrefix=\"none\" VpcStackName=\"backend-vpc\" CommonStackName=\"common-cri-api\""
image_repositories = []
