version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "cic-cri-api-2193b"
s3_prefix = "cic-cri-api"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CodeSigningConfigArn=\"none\" Environment=\"dev\" PermissionsBoundary=\"none\" SecretPrefix=\"none\" VpcStackName=\"vpc-cri\" L2DynamoStackName=\"cic-cri-ddb\" L2KMSStackName=\"cic-cri-kms\""
image_repositories = []
