version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "cic-test-harness"
s3_prefix = "cic-test-harness"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "CodeSigningConfigArn=\"none\" Environment=\"dev\" PermissionsBoundary=\"none\" SecretPrefix=\"none\" VpcStackName=\"vpc-cri\" BackendStack=\"cic-cri-api-kr\""
image_repositories = []
