name: Pull Request CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" or "develop" branch
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Required for sam-validate step
permissions:
  id-token: write
  contents: read

# Need to confirm where these should be stored
# env:
#   SESSION_TABLE_NAME: "test"
#   AUTHORIZATION_CODE_TABLE_NAME: "test"
#   AUTHORIZATION_CODE_TTL: "test"
#   REGION: "test"
#   ENVIRONMENT: "test"
#   ISSUER: "test"
#   SQS_QUEUE: "test"
#   TXMA_ENABLED: "false"

jobs:
  sam-validate:
    name: SAM Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: lambdafunctions
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        # Need to confirm whether submodules can be removed or not
        # with:
        #   submodules: true
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.56.0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          # is Dev role secrets config necessary for us
          role-to-assume: ${{ secrets.DEV_AWS_ROLE_TO_ASSUME }}
      - name: SAM Validate
        run: |
          sam validate
      - name: SAM Build
        run: |
          sam build
  # sonarcloud:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         # Disabling shallow clone is recommended for improving relevancy of reporting
  #         fetch-depth: 0
  #     - name: SonarCloud Scan
  #       uses: sonarsource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  run-unit-tests:
    name: Lint + Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: lambdafunctions
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.DEV_AWS_ROLE_TO_ASSUME }}
      - name: Check out repository code
        uses: actions/checkout@v2
        # Need to confirm whether submodules can be removed or not
        # with:
        #   submodules: true
      - name: Setup nodeJS v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install yarn
        run: npm -g install yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn
      - name: Run lint
        run: yarn run lint:check
      - name: Run Tests
        run: yarn run test:unit --passWithNoTests
      - name: Run Infra checks
        run: yarn run test:infra --passWithNoTests